<?php

/**
 * @file
 * Pega search and replace module.
 */

/**
 * Batch operation for batch replace.
 */
function batch_pega_search_replace($data, $operation_details, &$context) {
  foreach ($data['table'] as $item) {
    $entityData = explode("::", $item);
    $entityType = $entityData[1];
    $entityId = $entityData[0];
    $entityField = $entityData[2];

    $entity = \Drupal::entityTypeManager()->getStorage($entityType)->load($entityId);
    if (!empty($entity)) {
      $fieldValue = $entity->get($entityField)->value;
      $fieldValue = str_replace($data['search_string'], $data['replace'], $fieldValue);
      $entity->set($entityField, $fieldValue);
      $entity->save();
      $context['results'][] = $entityId;
    }
  }

  // Optional message displayed under the progressbar.
  $context['message'] = t('Running Batch "@id" @details',
    ['@id' => $entityId, '@details' => $operation_details]
  );
}


/**
 * Batch 'finished' callback.
 */
function batch_pega_search_replace_finished($success, $results, $operations) {
  $messenger = \Drupal::messenger();
  if ($success) {
    $messenger->addMessage(t('@count results processed.', ['@count' => count($results)]));
    $messenger->addMessage(t('The last processed entity ID was "%final"', ['%final' => end($results)]));
  }
  else {
    // An error occurred.
    // $operations contains the operations that remained unprocessed.
    $error_operation = reset($operations);
    $messenger->addMessage(
      t('An error occurred while processing @operation with arguments : @args',
        [
          '@operation' => $error_operation[0],
          '@args' => print_r($error_operation[0], TRUE),
        ]
      )
    );
  }
}

